#### Basic parameters ########

save_data: True                          ## Whether to save the dataset

#### Camera Parameters ##########
camera_serial_id: 'f1231454'             # Serial number of the depth camera used for terrain mapping
depth_width: 320
depth_height: 240
L515_pre_processing_sharpening: 3.0      # Internal sharpening of the depth image by the camera
L515_laser_power: 100.0                  # Laser power
L515_confidence_threshold: 2.0           # Confidence threshold (meaning unclear)

## Depth camera intrinsics
depth_fx: 228.686
depth_fy: 230.078
depth_cx: 157.748
depth_cy: 123.968

rgb_width: 640              # RGB image is used for display only
rgb_height: 480

#### Image Processing ###########

anisotropic_diffusion_num_iter: 60       # Number of iterations for anisotropic diffusion filtering
anisotropic_diffusion_kappa: 134
anisotropic_diffusion_gamma: 2

use_sharpening: True                     # Sharpen normal map before edge detection

Canny_thresh1: 50
Canny_thresh2: 100                       # thresh2 should be greater than thresh1

closing_kernel: 13                       # Size of the closing operation kernel for closing overly blurred edges

### RANSAC Parameters
ran_max_trials: 20                       ## Number of RANSAC fitting attempts
ran_min_samples: 3                       ## Minimum of 3 points required to fit a plane in RANSAC
ran_residual_threshold: 0.01             ## Inlier distance threshold (m)
ran_outlier_threshold: 0.05              ## Outlier tolerance ratio

#### Map Manager #########

min_area_thresh: 5000                    # Polygons with pixel area below this threshold will be ignored
merge_dis_thresh: 0.05                   # Distance threshold for merging polygons (m)

map_frame: 'world'                       # The map frame used by the odometry source
camera_frame: 'camera2_depth'
